"""Deterministic GEN0 SongProgram resolvers."""

from .compiler import (
    CompileError,
    CompilerIdentity,
    Gen0BCompileArtifacts,
    build_lineage_index,
    compile_direct_sp0,
    compile_connected_gen0b,
    compile_gen0b,
    compile_gen0b_report,
    compile_sp0,
    initial_material_lineage_seeds,
)
from .connected import (
    ConnectedCache,
    ConnectedExecution,
    ConnectedExecutionError,
    artifact_hash as connected_artifact_hash,
    build_cache_entry,
    execute_connected,
    run_connected_batch,
    validate_cache_entry,
)
from .resolver import resolve_joint_bnb, resolve_progression
from .renderer import RenderError, RenderResult, render_reference
from .search import (
    ArchiveCandidate,
    LocalRunStore,
    ProductionSearchLoop,
    SearchLoopError,
    SearchLoopResult,
    SearchLoopSeams,
    action_id,
    canonical_bytes,
    descriptor_values,
    descriptor_result_from_project,
    fingerprint_distance_q,
    fingerprint_payloads_from_project,
    fingerprint_record,
    fingerprint_record_from_project,
    manifest_digest,
    sampler_choice,
    seal_record,
    update_archive_record,
)
from .validator import ProjectValidationError, validate_project

__all__ = [
    "ArchiveCandidate",
    "CompileError",
    "CompilerIdentity",
    "Gen0BCompileArtifacts",
    "ConnectedCache",
    "ConnectedExecution",
    "ConnectedExecutionError",
    "LocalRunStore",
    "ProductionSearchLoop",
    "RenderError",
    "RenderResult",
    "SearchLoopError",
    "SearchLoopResult",
    "SearchLoopSeams",
    "ProjectValidationError",
    "action_id",
    "canonical_bytes",
    "build_lineage_index",
    "build_cache_entry",
    "compile_direct_sp0",
    "compile_connected_gen0b",
    "compile_gen0b",
    "compile_gen0b_report",
    "compile_sp0",
    "connected_artifact_hash",
    "descriptor_values",
    "execute_connected",
    "descriptor_result_from_project",
    "fingerprint_distance_q",
    "fingerprint_payloads_from_project",
    "fingerprint_record",
    "fingerprint_record_from_project",
    "manifest_digest",
    "initial_material_lineage_seeds",
    "resolve_joint_bnb",
    "resolve_progression",
    "render_reference",
    "run_connected_batch",
    "sampler_choice",
    "seal_record",
    "update_archive_record",
    "validate_cache_entry",
    "validate_project",
]
