"""Build role/lane MIDI stems and a hash-bound Vital/REAPER handoff manifest."""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from app.songprogram.midi_export import export_evaluation_midi  # noqa: E402
from app.songprogram.search import canonical_bytes  # noqa: E402


PRESET_BY_STEM = {
    "drums_kick": "PI 09 Pop Kick.vital",
    "drums_snare": "PI 10 Pop Snare.vital",
    "drums_clap": "PI 23 Noise Clap.vital",
    "drums_closed_hat": "PI 11 Pop Closed Hat.vital",
    "drums_open_hat": "PI 24 Noise Open Hat.vital",
    "drums_fill": "PI 12 Pop Perc.vital",
    "bass": "PI 20 Minimal Pulse.vital",
    "harmony": "PI 18 Future Chord Stack.vital",
    "melody": "PI 15 13-Limit Chorus Lead.vital",
    "texture_pad": "PI 13 Fifth Keys.vital",
    "texture_noise_riser": "PI 26 Noise Riser.vital",
    "texture_fx_impact": "PI 25 Noise Impact.vital",
    "texture_transition_tail": "PI 27 Noise Transition Tail.vital",
    "texture_arp": "PI 21 Sparkle Bell.vital",
    "texture_vocal_chop": "PI 19 Fractional Vocal Guide.vital",
    "texture_counterline": "PI 15 13-Limit Chorus Lead.vital",
    "texture_pluck": "PI 17 Candy Pluck.vital",
}
DRUM_STEM = {36: "drums_kick", 38: "drums_snare", 39: "drums_clap", 42: "drums_closed_hat", 46: "drums_open_hat", 45: "drums_fill"}
VITAL_USER_PRESETS = Path.home() / "Music" / "Vital" / "User" / "Presets"


def _sha(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def _texture_stem(event: dict, instances: dict[str, dict]) -> str:
    material = instances[event["source"]["material_instance_id"]]["material_id"]
    for mode in ("noise_riser", "fx_impact", "transition_tail", "vocal_chop", "counterline", "pluck", "arp", "pad"):
        if material.endswith(mode):
            return f"texture_{mode}"
    return "texture_pad"


def _lua_string(value: str) -> str:
    return json.dumps(value)


def _reaper_script(assignments: list[dict], output: Path) -> str:
    project_path = str((output / "vital_preview.rpp").resolve())
    rows = []
    for row in assignments:
        rows.append(
            "  { stem = %s, midi = %s, preset = %s, preset_path = %s },"
            % (
                _lua_string(row["stem"]),
                _lua_string(str((output / row["midi_path"]).resolve())),
                _lua_string(Path(row["preset_path"]).stem),
                _lua_string(str((BACKEND.parent / row["preset_path"]).resolve())),
            )
        )
    mismatches = [Path(row["preset_path"]).stem for row in assignments if not row["preset_installed"]]
    preflight = (
        "error(%s)" % _lua_string("VITAL_PRESET_HASH_MISMATCH:" + ",".join(mismatches))
        if mismatches else "-- preset hash preflight passed"
    )
    return """-- Generated by CPS. Run once from REAPER's ReaScript action list.
local tracks = {
%s
}
%s
local b64chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
local function b64decode(data)
  data = string.gsub(data, "[^" .. b64chars .. "=]", "")
  return (string.gsub(data, ".", function(char)
    if char == "=" then return "" end
    local value = string.find(b64chars, char, 1, true) - 1
    local bits = ""
    for index = 5, 0, -1 do bits = bits .. (math.floor(value / 2 ^ index) %% 2) end
    return bits
  end):gsub("%%d%%d%%d%%d%%d%%d%%d%%d", function(byte)
    local value = 0
    for index = 1, 8 do value = value + tonumber(string.sub(byte, index, index)) * 2 ^ (8 - index) end
    return string.char(value)
  end))
end
local function b64encode(data)
  return ((data:gsub(".", function(char)
    local value = string.byte(char)
    local bits = ""
    for index = 7, 0, -1 do bits = bits .. (math.floor(value / 2 ^ index) %% 2) end
    return bits
  end) .. "0000"):gsub("%%d%%d%%d?%%d?%%d?%%d?", function(chunk)
    if #chunk < 6 then return "" end
    local value = 0
    for index = 1, 6 do value = value + tonumber(string.sub(chunk, index, index)) * 2 ^ (6 - index) end
    return string.sub(b64chars, value + 1, value + 1)
  end) .. ({ "", "==", "=" })[#data %% 3 + 1])
end
local function u32le(data, offset)
  local a, b, c, d = string.byte(data, offset + 1, offset + 4)
  return a + b * 256 + c * 65536 + d * 16777216
end
local function u32be(data, offset)
  local a, b, c, d = string.byte(data, offset + 1, offset + 4)
  return d + c * 256 + b * 65536 + a * 16777216
end
local function pack_u32le(value)
  return string.char(value %% 256, math.floor(value / 256) %% 256, math.floor(value / 65536) %% 256, math.floor(value / 16777216) %% 256)
end
local function pack_u32be(value)
  return string.char(math.floor(value / 16777216) %% 256, math.floor(value / 65536) %% 256, math.floor(value / 256) %% 256, value %% 256)
end
local function replace_u32(data, offset, packed)
  return string.sub(data, 1, offset) .. packed .. string.sub(data, offset + 5)
end
local function read_file(path)
  local file = assert(io.open(path, "rb"), "VITAL_PRESET_READ_FAILED:" .. path)
  local payload = file:read("*a")
  file:close()
  return payload
end
local function apply_vital_preset(track, fx, path, preset_name)
  local ok, encoded = reaper.TrackFX_GetNamedConfigParm(track, fx, "vst_chunk")
  if not ok then error("VITAL_CHUNK_READ_FAILED:" .. preset_name) end
  local chunk = b64decode(encoded)
  local json_start = string.find(chunk, "{", 1, true)
  local json_end = nil
  for index = #chunk, 1, -1 do
    if string.sub(chunk, index, index) == "}" then json_end = index break end
  end
  if not json_start or not json_end then error("VITAL_CHUNK_LAYOUT_UNKNOWN:" .. preset_name) end
  local preset = read_file(path)
  local old_size = json_end - json_start + 1
  local delta = #preset - old_size
  chunk = string.sub(chunk, 1, json_start - 1) .. preset .. string.sub(chunk, json_end + 1)
  chunk = replace_u32(chunk, 0, pack_u32le(u32le(chunk, 0) + delta))
  chunk = replace_u32(chunk, 28, pack_u32be(u32be(chunk, 28) + delta))
  chunk = replace_u32(chunk, 180, pack_u32be(u32be(chunk, 180) + delta))
  if not reaper.TrackFX_SetNamedConfigParm(track, fx, "vst_chunk", b64encode(chunk)) then
    error("VITAL_CHUNK_WRITE_FAILED:" .. preset_name)
  end
end
reaper.Undo_BeginBlock()
reaper.Main_OnCommand(40859, 0)
reaper.GetSetProjectInfo(0, "PROJECT_SRATE", 48000, true)
reaper.GetSetProjectInfo(0, "RENDER_SRATE", 48000, true)
reaper.GetSetProjectInfo(0, "RENDER_CHANNELS", 2, true)
for index, row in ipairs(tracks) do
  reaper.InsertTrackAtIndex(index - 1, true)
  local track = reaper.GetTrack(0, index - 1)
  reaper.GetSetMediaTrackInfo_String(track, "P_NAME", row.stem, true)
  reaper.SetOnlyTrackSelected(track)
  reaper.SetEditCurPos(0, false, false)
  reaper.InsertMedia(row.midi, 0)
  local fx = reaper.TrackFX_AddByName(track, "VST3i: Vital (Vital Audio)", false, 1)
  if fx < 0 then error("VITAL_PLUGIN_NOT_FOUND:" .. row.stem) end
  apply_vital_preset(track, fx, row.preset_path, row.preset)
end
reaper.Main_SaveProjectEx(0, %s, 0)
reaper.Undo_EndBlock("Build CPS Vital preview project", -1)
reaper.UpdateArrange()
reaper.ShowMessageBox("Vital preview project created. Verify each preset, then render the master to perceptual_preview.wav.", "CPS Vital", 0)
""" % ("\n".join(rows), preflight, _lua_string(project_path))


def build(song_directory: Path, output: Path, preset_directory: Path) -> dict:
    project = json.loads((song_directory / "project.json").read_text())
    tracks = {track["id"]: track for track in project["tracks"]}
    instances = {row["id"]: row for row in project["material_instances"]}
    events_by_stem: dict[str, list[dict]] = {}
    for event in project["events"]:
        role = tracks[event["track_id"]]["role"]
        stem = (
            DRUM_STEM[event["drum_note"]]
            if role == "drums"
            else _texture_stem(event, instances) if role == "texture" else role
        )
        events_by_stem.setdefault(stem, []).append(event)

    midi_directory = output / "midi"
    midi_directory.mkdir(parents=True, exist_ok=True)
    assignments = []
    for stem in sorted(events_by_stem):
        preset_name = PRESET_BY_STEM[stem]
        preset_path = preset_directory / preset_name
        if not preset_path.is_file():
            raise ValueError(f"VITAL_PRESET_MISSING:{preset_name}")
        stem_project = copy.deepcopy(project)
        stem_project["events"] = events_by_stem[stem]
        if stem.startswith("drums_"):
            for event in stem_project["events"]:
                event["drum_note"] = 60
        midi, midi_manifest = export_evaluation_midi(
            stem_project,
            pitched_channels=tuple(channel for channel in range(1, 16) if channel != 9),
            algorithm="smf0-mpe-lower-zone/v1",
        )
        midi_name = f"{stem}.mid"
        (midi_directory / midi_name).write_bytes(midi)
        assignments.append(
            {
                "stem": stem,
                "event_count": len(events_by_stem[stem]),
                "midi_path": f"midi/{midi_name}",
                "midi_hash": midi_manifest["midi_hash"],
                "preset_path": f"backend/app/static/vital_presets/{preset_name}",
                "preset_hash": _sha(preset_path.read_bytes()),
                "preset_installed": (
                    (VITAL_USER_PRESETS / preset_name).is_file()
                    and _sha((VITAL_USER_PRESETS / preset_name).read_bytes())
                    == _sha(preset_path.read_bytes())
                ),
            }
        )
    script = _reaper_script(assignments, output)
    (output / "setup_reaper.lua").write_text(script)
    render_path = output / "perceptual_preview.wav"
    manifest = {
        "schema": "cps.vital-preview-render-manifest",
        "schema_version": "1.0.0",
        "status": "rendered" if render_path.is_file() else "render_pending",
        "host": {"id": "reaper", "application_path": "/Applications/REAPER.app"},
        "plugin": {"id": "vital-vst3", "bundle_path": "/Library/Audio/Plug-Ins/VST3/Vital.vst3"},
        "sample_rate": 48000,
        "channel_layout": "stereo",
        "mpe": {
            "mode": "lower-zone-member-channels-with-drum-channel-excluded/v1",
            "master_channel": 1,
            "member_channels": [2, 16],
            "excluded_channel": 10,
            "pitch_bend_range_semitones": 2
        },
        "source_project_hash": _sha((song_directory / "project.json").read_bytes()),
        "assignments": assignments,
        "reaper_bootstrap": {
            "script_path": "setup_reaper.lua",
            "script_hash": _sha(script.encode()),
            "project_path": "vital_preview.rpp",
            "output_path": "perceptual_preview.wav"
        },
        "render_output": (
            {
                "path": "perceptual_preview.wav",
                "pcm_container_hash": _sha(render_path.read_bytes()),
                "byte_length": render_path.stat().st_size,
            }
            if render_path.is_file()
            else None
        ),
        "manifest_hash": "",
    }
    manifest["manifest_hash"] = _sha(
        b"cps.vital-preview-render-manifest/v1\0"
        + canonical_bytes({key: value for key, value in manifest.items() if key != "manifest_hash"})
    )
    (output / "vital_render_manifest.json").write_bytes(canonical_bytes(manifest))
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("song_directory", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--preset-directory", type=Path, default=BACKEND / "app" / "static" / "vital_presets")
    arguments = parser.parse_args()
    print(json.dumps(build(arguments.song_directory, arguments.output, arguments.preset_directory), separators=(",", ":")))


if __name__ == "__main__":
    main()
