from __future__ import annotations

from fractions import Fraction

from app.tuning.ratios import ratio_text


def scala_text(name: str, ratios: list[Fraction]) -> str:
    unique = sorted(set(ratios))
    entries = [ratio for ratio in unique if ratio != 1]
    lines = [f"! {name}.scl", "! Generated by Pure Intonation Workbench", name, str(len(entries))]
    lines.extend(ratio_text(ratio) for ratio in entries)
    return "\n".join(lines) + "\n"
